### PR TITLE
Update to Chaos Calmer/add new targets

### PR DESCRIPTION
**Pull request by sarumpaet**
This updates to CC/OpenWrt trunk, adds support for the Nexx WT3020, the GL.iNet 6416A, and builds olsrd2.

### CODE REVIEW

**Comment by booo** [comment]
I prefer to wait for a "stable" release of openwrt. Are there any reasons why we should experiment with the release candidate?

**Comment by sarumpaet** [comment]
The idea is to base the next (0.2) kathleen release not on Barrier Breaker anymore but to update. As you can see in the commits, many features I worked on already depend on CC. We can update the OpenWrt base again later (to the actual release or whatever).

**Comment by booo** [comment]
At the moment there is a automatic redirect from http to https. I think we should disable this otherwise we get a lot of confused users. @sarumpaet Did you look at this already?

**Comment by booo** [comment]
For the https problem we have to change the `/etc/config/uhttpd` configuration file. The option we need to change: `option redirect_https '1'` Should be zero.

Should rpcd be part of the standard image? It is at the moment. Do we need it for something? If not I suggest we remove rpcd from the standard image and build it as module.

**Comment by booo** [comment]
There is this strange new ip rule. Any idea where this rule comes from? There is no table 128 as far as I can see.
```
root@node01:~# ip rule
0:	from all lookup 128 
...
```

**Comment by lynxis** [comment]
@sarumpaet please reword your commits. Don't use "see #123" because ticket might be change in future and referencing only to tickets is a bad idea. Do a full commit description to it.

**Comment by lynxis** [comment]
CC released.

**Comment by booo** [comment]
Ich hätte ja die ausstehenden Probleme gelöst und dann den Branche gemerged, aber gut...

**Comment by booo** [comment]
Rpcd dependency was introduced by a commit in the luci repository: https://github.com/openwrt/luci/commit/199c8cbc4c32506ecfe89850615b88a3f0276dd3

**Pull request merged**
