### PR TITLE
Use modules-file instead of generating it from config.mk and feeds.conf

### PR DESCRIPTION
**Pull request by SvenRoederer**
The modules-file controls which code of the upstream-repos is used. With the implementation of PR #714 we added some "glue-code" to create the ```modules``` file from the currently used files (```config.mk```, ```feeds.conf```). 
This "glue-code" works well with the official Upstream-repos but seems to have some problems with alternative repos as shown by issue #780. This PR drops the "very brittle" code and moves the repo-definitions to ```modules``` directly.

* Drops the additional converting code
* speeds up build, by not copying each repo an additional time to find the branch of the referencing commit
* moves the definition of any upstream-repo into a single file (not spread around two files anymore)
* an instant lookup of the branch, the code firmware-build is based on, is possible

### CODE REVIEW

**Comment by pmelange** [comment]
I am currently building with these changes cherry-picked into a private branch of the "next" branch.  The goal is to prototype kernel 5.4 on the erx-sfp.  

One thing that I noticed, is that I have to put a commit ID into the modules file.  If not, I get the following error:

```
Initialized empty Git repository in /home/pmelange/src/mt7621/openwrt/.git/     
remote: Enumerating objects: 2, done.                                           
remote: Counting objects: 100% (2/2), done.                                     
remote: Compressing objects: 100% (2/2), done.                                  
remote: Total 488150 (delta 0), reused 0 (delta 0), pack-reused 488148          
Receiving objects: 100% (488150/488150), 171.31 MiB | 5.21 MiB/s, done.         
Resolving deltas: 100% (332298/332298), done.                                   
From https://github.com/vDorst/openwrt                                          
 * branch            ramips-5.4 -> FETCH_HEAD                                   
fatal: Not a valid object name: ''.                                             
unable to find commit "" on branch "ramips-5.4" in repo "https://github.com/vDor
st/openwrt.git".                                                                
make: *** [Makefile:90: .stamp-pre-patch] Error 1                               
```

It would be really cool if this code would use the HEAD of the branch if no commit-id is given.

So, I would say that this fixes issue #780, but not #477

**Comment by pmelange** [comment]
Running "make clean" deletes the modules file.  Afterwards running make again results in
```
rm -f /home/pmelange/src/mt7621/openwrt/.config
rm -f .stamp-
make: *** No rule to make target '/home/pmelange/src/mt7621/modules', needed by '.stamp-pre-patch'.  Stop.
```

Also, it seems like that if I change the commit-id (for example in luci) in the modules file, and run make again, then the new commits are not integrated and built.

**Comment by SvenRoederer** [comment]
fixed in 3443833

**Comment by SvenRoederer** [comment]
Any additional feedback?
What about merging this?

**Comment by pmelange** [comment]
I still haven't gotten around to testing alternative git repos. Specifically I would like to try the equivalent of src-lnk, which I have found to be very useful for prototyping

**Comment by Akira25** [comment]
I havn't test this, but I like the goals to be achieved by this PR. Sounds like a good Idea.

**Comment by pmelange** [comment]
I'm having trouble being able to use alternative git feed types.  How are we supposed to be able to use the different types of feeds support by openwrt and shown here: https://openwrt.org/docs/guide-developer/feeds

**Comment by SvenRoederer** [comment]
this PR is only about solving the problem described in #780 (interpreting external GIT repos from config.mk and feeds.conf to build the modules-file). In addition this PR should also fix #772. 
We should avios to use a solution for an issue (here #780) to solve another different issue (#777 ) too. Even both issues somehow relate to each other.

**Comment by SvenRoederer** [comment]
> I'm having trouble being able to use alternative git feed types. How are we supposed to be able to use the different types of feeds support by openwrt and shown here: https://openwrt.org/docs/guide-developer/feeds

@pmelange can you put this into a separate issue?

**Comment by pmelange** [comment]
> > I'm having trouble being able to use alternative git feed types. How are we supposed to be able to use the different types of feeds support by openwrt and shown here: https://openwrt.org/docs/guide-developer/feeds
> 
> @pmelange can you put this into a separate issue?

See issue #789

**Comment by SvenRoederer** [comment]
Independent of fix for issue #789 this PR will solve the #780 & #772 already.

**Comment by SvenRoederer** [comment]
I'm going to merge this by this week, as it solves to issues and doesn't break anything. I tested it for some time in the "SAm0815-experimental" branches.

**Comment by SvenRoederer** [comment]
merged into master with 487cb331c1d48e5f4b092470e7b24032f4691c0b and c6aa875f091a3c08065a2e960729d422a6fda122.

**Pull request closed without merging**
