### PR TITLE
config.mk: update openwrt revision

### PR DESCRIPTION
**Pull request by booo**
Includes security updates for e.g. openssl. This should fix the broken openssl
in the current master too.

### CODE REVIEW

**Comment by lynxis** [comment]
@booo please include a small Changelog (git log --oneline) into the commit message.

**Comment by sarumpaet** [comment]
Hm, shouldn't we base the next (0.2) release on something newer than Barrier Breaker? See https://github.com/freifunk-berlin/firmware/pull/264 .

**Comment by lynxis** [comment]
@sarumpaet I would like to do a release on 0.2. afterwards we change to chaos calmer.

**Comment by sarumpaet** [comment]
What do you want to change for the 0.2 then?

**Comment by booo** [comment]
I attached a short log to the commit body.

Maybe we should just push a minor release and upgrade to chaos calmer with a major release afterwards. I don't think it's a good idea to base a stable release on an unstable release candidate.

**Comment by sarumpaet** [comment]
I don't quite see the point in making an extra BB-based release. Do we actually use OpenSSL anywhere? We use PolarSSL for OpenVPN and uhttpd as far as I can see. If you really want to make another BB release, please use 0.1.3. Merging in master/0.2.0 is of course also okay, but the CC merge will overwrite this anyways.

**Pull request closed without merging**
