### PR TITLE
strip firmware size

### PR DESCRIPTION
**Pull request by cholin**
As there are routers with 4MB in the wild and we do offer firmwares on http://berlin.freifunk.net/downloads/ I would be happy if we could reduce the size for these devices. With this pull request I added the following changes:

* remove `iwinfo` and `luci-app-owm-gui` packages for 4MB devices
* remove `obsolete freifunk-gwcheck` package (this functionality has been replaced with olsrd gateway check plugin)
* remove ssp support
* activate `CONFIG_STRIP_KERNEL_EXPORTS` (unnecessary / unlinked functions in the kernel itself will be removed)

Support for stack smashing protection got merged with 6318d5a. As there is no package which supports SSP at the moment in the Freifunk Firmware Berlin this functionality is obsolete and can be deleted for size and complexity reasons (see #107 and #191 (comment)).

I tested this with a TP-Link 841n v8 and got 48KB. Before there was 96KB of free space and afterwards 144KB.

### CODE REVIEW

**Comment by lgierth** [comment]
I agree that SSP should be removed.

**Comment by cholin** [comment]
With the last changes I got  156KB (additional 12KB) on a TP-LINK 741:

```
root@OpenWrt:~# df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                  384.0K    228.0K    156.0K  59% /
/dev/root                 3.0M      3.0M         0 100% /rom
tmpfs                    14.4M    172.0K     14.2M   1% /tmp
tmpfs                    14.4M     88.0K     14.3M   1% /tmp/root
tmpfs                   512.0K         0    512.0K   0% /dev
/dev/mtdblock3          384.0K    228.0K    156.0K  59% /overlay
overlayfs:/overlay      384.0K    228.0K    156.0K  59% /
```

Hard to test which change are worth the effort because I don't have a device on my own here. How do we want to proceed? Is anyone interested into getting (some of) this changes upstream to better support these 4MB devices?

**Comment by booo** [comment]
I have a spare 841ND if you need some test hardware.

To me the consequences of stripping the kernel and changing the block size of the squashfs are not clear.

If you really thing this is useful let's merge it!

**Comment by cholin** [comment]
I think we should evaluate each commit and than think again if we want this for our target `ar71xx`. Some commits may do not result in that big amount of free space or limit us in another way. Some words on kernel stripping and block size for squashfs:

* kernel stripping: not needed kernel functionality will be removed. This may result in non-functional behaviour for kernel modules which got installed later via opkg (see as well https://forum.openwrt.org/viewtopic.php?pid=182963#p182963)

* squash fs blocksize: Higher block sizes for squashfs will result in smaller space consumption. The reason for that is the bigger the block size the better the compression and therefor smaller partition size.

**Comment by cholin** [comment]
Seems I forgotten to paste `df -h` output of https://github.com/freifunk-berlin/firmware/commit/b9f3531aa548ff7073c5380dfeeca869ec070c7d:

```
root@OpenWrt:~# df -h
Filesystem                Size      Used Available Use% Mounted on
rootfs                  448.0K    228.0K    220.0K  51% /
/dev/root                 2.5M      2.5M         0 100% /rom
tmpfs                    14.4M    160.0K     14.2M   1% /tmp
tmpfs                    14.4M     88.0K     14.3M   1% /tmp/root
tmpfs                   512.0K         0    512.0K   0% /dev
/dev/mtdblock3          448.0K    228.0K    220.0K  51% /overlay
overlayfs:/overlay      448.0K    228.0K    220.0K  51% /
```

It results in additional 64KB (in total 220KB).

**Comment by research7** [comment]
Maybe, my experience using the patch on a wrt841nd v9 is of some help. thus, I repost some info from #191:

Works on wrt841nd
===
I applied the suggested changes to master, build the image, flashed, and things work fine now!
Addition
===
in order to make the Freifunkassitent work I had to scp profile_berlin to /etc/config


Space left after successful flashing and configuration
===
Filesystem Size Used Available Use% Mounted on
rootfs 384.0K 236.0K 148.0K 61% /
/dev/root 2.5M 2.5M 0 100% /rom
tmpfs 14.3M 176.0K 14.2M 1% /tmp
/dev/mtdblock3 384.0K 236.0K 148.0K 61% /overlay
overlayfs:/overlay 384.0K 236.0K 148.0K 61% /
tmpfs 512.0K 0 512.0K 0% /dev

**Comment by sarumpaet** [comment]
On a WR841N v8, I got this:
Filesystem Size Used Available Use% Mounted on
overlayfs:/overlay      448.0K    220.0K    228.0K  49% /
Doing some "dd if=/dev/urandom" in the overlay was okay up to 3x64k, then the space was exhausted, but deleting files in the overlay still worked (in contrast to kathleen 0.0.0).

So, well done!

I also tried without CONFIG_STRIP_KERNEL_EXPORTS, but this reduces the overlay size from 440k to 384k and free space below the 3x64k mark.

Would it be possible to have a special kernel configuration for 4MB devices only?

**Comment by cholin** [comment]
This PR is not up-to-date anymore and contains changes we may do not want. I close this for now and recommend to focus on https://github.com/freifunk-berlin/firmware/issues/52#issuecomment-75763624 instead.

**Comment by cholin** [comment]
Please do not delete this branch. I may cherry-pick some commits for another PR.

**Comment by lgierth** [comment]
Have you tried the following? It helped me get the cjdns image below the 3473408 bytes mandated by the Netgear's factory partitioning.

```
CONFIG_STRIP_KERNEL_EXPORTS=y # Strip unnecessary exports from the kernel image
CONFIG_USE_MKLIBS=y # Strip unnecessary functions from libraries
```

**Comment by lgierth** [comment]
Nevermind, you did.

**Comment by cholin** [comment]
Yeah. Already included (see commit list).

**Pull request closed without merging**
