### PR TITLE
patches: patch mbedtls to allow 1024 bits RSA

### PR DESCRIPTION
**Pull request by sarumpaet**
Patch mbedtls to allow 1024 bits RSA
for bbb-vpn and VPN03 compatibility

fixes https://github.com/freifunk-berlin/firmware/issues/489

### CODE REVIEW

**Comment by pmelange** [comment]
Wasn't this already merged?  Can we close this PR?

**Comment by sarumpaet** [comment]
This PR is still open: The change is in master already, but not in 
Hedy-1.0.2, which this PR is for.

Also, this needs rebasing now; apparently there was some force pushing 
going on in the 1.0.2 branch or something. This PR is only one commit 
actually. Will do that and merge later this week if nobody else does it.

**Comment by pmelange** [comment]
I don't think that the 1.0.2 branch is being worked on by anyone.  And when it will be worked on, individual commits from the master branch will be merged into the 1.0.2 branch.

But it doesn't matter to me how the PR goes.  I just thought about cleaning up a bit of clutter.

**Comment by sarumpaet** [comment]
I cherry-picked the master commit to bb35c32. Closing this and deleting the branch.

**Pull request closed without merging**
