### PR TITLE
Update openwrt-routing/packages feed.

### PR DESCRIPTION
**Pull request by stspdotname**
Suggested by booo in https://github.com/freifunk-berlin/firmware/pull/333

### CODE REVIEW

**Comment by booo** [comment]
Looks good. Thanks again!

**Comment by SvenRoederer** [comment]
is it really a "safe" idea to switch from "for15.05"-branch to master?
as the Freifunk-firmware is based on 15.05-release the "for15.05"-branch should match.
Not sure on the sideeffects using the "trunk" version of routing feed, which may aimed to OpenWRT trunk also.

**Comment by stspdotname** [comment]
feeds.conf has been tracking the master branch of openwrt-routing/packages for quite a while, since 00b8ba8cf975d08cd085ff50ea2967096d8271bb

**Comment by SvenRoederer** [comment]
@stspdotname oh, never checked this out ... thanks for pointing

**Pull request merged**
