### PR TITLE
switch to LEDE as base for next release

### PR DESCRIPTION
**Pull request by SvenRoederer**
- OpenWrt-development is nearly stuck 
- LEDE is going to release "LEDE-17.01"

As here are picked commits reaching back to may 2016 do not merge this, please rebase this onto master!

### CODE REVIEW

**Comment by SvenRoederer** [comment]
@lynxis you are right.
This is just a PR of my working-base, as I'd like to collect feedback before investing time in cleaning up the commits.

So, I'll wait some more days for feedback and then start to rebase that this can be merged.

**Comment by booo** [comment]
Please create a clean and minimal pull request for the switch to LEDE and then we start the review process.

I think it is consensus to switch to LEDE as soon as there is a stable release for LEDE.

**Comment by SvenRoederer** [comment]
please check again, think ready to merge. More squashing I'll avoid.

slaves are building now:
* ar71xx-generic: build# 93
* ar71xx-mikrotik: build# 87
* mpc85xx-generic: build# 86
* ramips-mt7620: build# 80
* x86-generic: build# 88

**Comment by booo** [comment]
What about the issues mentioned here: https://github.com/freifunk-berlin/firmware/issues/418

I think we should not enable telnet. The lede upstream configuration is fine to me.

The bbb-vpn is a non standard setup. We should stick to the mbedtls openvpn package as standard package for the standard firmware.

Do we have more information on the disk space problem?

**Comment by SvenRoederer** [comment]
The intention of #418 is only to collect the issues for the time LEDE is not the underlaying base. So these issues need to be solved

Without telnet, it will be hard to connect to legacy nodes like switches or modems which are not ssh-enabled. telnet is also useful for network debugging.

OpenVPN: VPN03 also uses RSA1024.

4MB: see https://lede-project.org/supported_devices and https://forum.lede-project.org/t/should-lede-support-devices-with-only-4mb-flash/1018

**Comment by SvenRoederer** [comment]
but most, if not all, the problems referenced in #418 we will also have with OpenWrt-DD, as this also uses the same feeds for packages, LuCI and Routing.
Only OpenVpn would work with current OpenWrt-master, but only as they still hang on the deprecated polarSSL

**Comment by SvenRoederer** [comment]
As per LEDE-devel ML the release of 17.01. comes close.
Are there any NACKs to merge this till / at the "Firmware+Wizard Hackathon 18.2. 14:00 @ PH HQ" ?

**Comment by SvenRoederer** [comment]
@booo:
- OpenVPN: use of the openssl-variant creates the most minimal issues with the currently rolled out structure. Certificates can be reused, user can switch to the new code w/o additional actions. the only point are the 4MB-devices, but there is a warning out long time already.
So this switch seems to me the most minimal diff regarding code and function.

@lynxis:
- px5g-embed-tls: fixed in recent force-push
- uhttpd-mod-tls: removed from config
- CONFIG_VERSION_CODE: I prefer to stay at the same style of code as we introduced in https://github.com/freifunk-berlin/firmware/blob/5a7fa79a1c4dc006cc5bc3c5cba8dd761a0ff1e4/Makefile#L86. Using the SED-style is probably the most minimal change. 
Even the SED-style is not the most beautiful code, but making it more nice I'd to leave for a commit out of the scope of the PR
- embedd files / banner: as it's in master, fixing this don't belong to this PR

**Comment by lynxis** [comment]
let's merge it now.
There still might some problems with the version_code, but the old behaviour isn't great anyway so. So we can fix this later.

**Pull request merged**
