### PR TITLE
wechsel auf OpenWRT-branch "master"

### PR DESCRIPTION
**Pull request by SvenRoederer**
Da ein OpenWRT-release 18.03 oder 18.04 geplant ist, sollten wir schon mal diesen Wechsel bei unserem Code vorbereiten.

Grundlegend funktioniert der Code, es gibt aber noch einige Bausstellen ... (https://github.com/freifunk-berlin/firmware/issues?q=is%3Aopen+is%3Aissue+milestone%3AHedy-1.1.0)

### CODE REVIEW

**Comment by SvenRoederer** [comment]
Any concerns with this step towards the new major release?

**Comment by booo** [comment]
Can you clean up the pull request a bit. Why does it contain e.g. "remove VPN03 flavor"? Maybe we can squash some commits?

Otherwise a good idea.

**Comment by SvenRoederer** [comment]
I already squashed the original commits in a way, that they are atomic. When on of these upstream changes required some change on our code such commit was added and then the upstream changes were continued.
VPN03 was removed as I expect this next major release to come after the VPN03-service is shut down and this also saves some buildtime (probably 25%).

**Comment by booo** [comment]
Could you please revert the change regarding the VPN03 package. The service will be in existence for at least until the end of the year and we need images for the service. Thanks a lot.

**Comment by SvenRoederer** [comment]
When the next major-release will come to a releaseable state long enough before VPN03 will shut down (e.g. 3 months), I'll happily revert this commit.
but for not I'll save the buildbot-ressources, as noted before.

**Pull request merged**
