### PR TITLE
embedd files directly into image, rather than patching

### PR DESCRIPTION
**Pull request by SvenRoederer**
This way we include the banner-file, and possible other files, directly and don't have to patch them.
So we can avoid some patching and pushing some changes to files is much more easy.

Verified to work in http://buildbot.berlin.freifunk.net/buildbot/unstable/mpc85xx/1092/ before squashing and rewording.

### CODE REVIEW

**Comment by SvenRoederer** [comment]
I consider merging in the next days, as this will avoid additional patching when switching to LEDE / upgraded OpenWrt-file

**Comment by booo** [comment]
Why don't we create symlinks to the toplevel directory of the files instead of coping the stuff around?

**Comment by SvenRoederer** [comment]
just did as we do currently for th patches (https://github.com/freifunk-berlin/firmware/blob/master/Makefile#L53)

**Comment by SvenRoederer** [comment]
forget about my last comment.

**Comment by SvenRoederer** [comment]
Think my idea was, "use copy, as you later can modify the file in the build-tree, w/o altering the originals".
But ... ????

Let'S do the link-way, as we do for patches

**Comment by SvenRoederer** [comment]
Hmm, I did not mention that I reworked the code correctly from copy to link?

**Comment by SvenRoederer** [comment]
I suggest to reset the tree and give me some time for correcting

**Comment by booo** [comment]
I suggest you either push a fix to the master branch or we revert the stuff. Force pushing to master is bad and github protects the master branch by a special hook as well.

As far as I can see there is a problem with the dependencies. Right?

**Comment by SvenRoederer** [comment]
forcing on master is bad - true. But it's not impossible ...
esp with this uuuugly commit - faulty, introduces unneeded code, a complete non-matching commit-message. And as @lynxis mentioned it looks more nice to rebase such single commit into master than merging it an generation 2 commit-messages

**Comment by booo** [comment]
I don't think a commit that fixes a mistake is that ugly. In the end mistakes happen and are part of the process.

But do as you please ;)

**Comment by SvenRoederer** [comment]
finally merged with https://github.com/freifunk-berlin/firmware/commit/a66896d3ca02d1aff22be0c5b77e812ebd7596d4

**Pull request merged**
