### PR TITLE
Feature: common config

### PR DESCRIPTION
**Pull request by SvenRoederer**
as seen in #06da8aa it may prevent some work to separate between arch-specific and common config-option.
- so only one file has to be modified normally
- and the images are more equal

### CODE REVIEW

**Comment by SvenRoederer** [comment]
this may help to keep the configurations of the differenct archs in sync

**Comment by booo** [comment]
I will take a closer look at this as soon as I find some time.

**Comment by SvenRoederer** [comment]
@booo as you merged PR https://github.com/freifunk-berlin/firmware/pull/317, did you had some time to look at this PR?
Getting this merged, will save some time, when a setting changes on all targets

**Comment by booo** [comment]
I think you moved configuration from a specific target to common. E.g. the CONFIG_PACKAGE_om-watchdog=m configuration that should only be present in ar71xx configuration. Can you please double check. Apart from this minor problem I think it's fine to merge this.

**Comment by SvenRoederer** [comment]
I'll show you some diffs between the original files and the result of the combined files tomorrow. Let's discuss this

**Pull request merged**
