### PR TITLE
add some Buffalos and WR1043v4 for ar71xx

### PR DESCRIPTION
**Pull request by SvenRoederer**
as of user-requests and the hardware looks not crappy

build is ín progress and this can be safely rebased then

### CODE REVIEW

**Comment by SvenRoederer** [comment]
@hafu had you a chance to check?

**Comment by hafu** [comment]
@SvenRoederer today I had some time to investigate. It looks like the images are build, but not moved to `firmwares/ar71xx-generic/default/`:
```
$ ls -l lede/bin/targets/ar71xx/generic/*wzr*
-rw-r--r-- 1 hannes hannes 3014860 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-450hp2-squashfs-factory.bin
-rw-r--r-- 1 hannes hannes 3014660 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-450hp2-squashfs-sysupgrade.bin
-rw-r--r-- 1 hannes hannes 3014692 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-450hp2-squashfs-tftp.bin
-rw-r--r-- 1 hannes hannes 3014860 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-600dhp-squashfs-factory.bin
-rw-r--r-- 1 hannes hannes 3014660 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-600dhp-squashfs-sysupgrade.bin
-rw-r--r-- 1 hannes hannes 3014692 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-600dhp-squashfs-tftp.bin
-rw-r--r-- 1 hannes hannes 3014864 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-hp-ag300h-squashfs-factory.bin
-rw-r--r-- 1 hannes hannes 3014660 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-hp-ag300h-squashfs-sysupgrade.bin
-rw-r--r-- 1 hannes hannes 3014692 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-hp-ag300h-squashfs-tftp.bin
-rw-r--r-- 1 hannes hannes 3014864 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-hp-g300nh2-squashfs-factory.bin
-rw-r--r-- 1 hannes hannes 3014660 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin
-rw-r--r-- 1 hannes hannes 3014692 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-hp-g300nh2-squashfs-tftp.bin
-rw-r--r-- 1 hannes hannes 3014864 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-hp-g300nh-squashfs-factory.bin
-rw-r--r-- 1 hannes hannes 3014660 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-hp-g300nh-squashfs-sysupgrade.bin
-rw-r--r-- 1 hannes hannes 3014692 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-hp-g300nh-squashfs-tftp.bin
-rw-r--r-- 1 hannes hannes 3014864 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-hp-g450h-squashfs-factory.bin
-rw-r--r-- 1 hannes hannes 3014660 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-hp-g450h-squashfs-sysupgrade.bin
-rw-r--r-- 1 hannes hannes 3014692 Mai 16 08:28 lede/bin/targets/ar71xx/generic/freifunk-berlin-1.0.0-alpha-ar71xx-generic-wzr-hp-g450h-squashfs-tftp.bin
```

I did not find anything useful in the logoutput (`make V=s | V=99`), so I assume something is missing/wrong in a makefile. Maybe it is a hint. I think it takes a bit for me to understand the build process and all the make files.

**Comment by SvenRoederer** [comment]
just created branch "more_ar71xx-targets_debug" with some additional "ls" to see what's going on

**Comment by SvenRoederer** [comment]
the relating logfile is
https://buildbot.berlin.freifunk.net/builders/ar71xx-generic/builds/252/steps/shell/logs/stdio

**Comment by SvenRoederer** [comment]
looks like they are build in LEDE.
Imagebuilder is creating an image also, but fails then:
```
mkimage -A mips -O linux -T kernel -a 0x80060000 -C lzma  -e 0x80060000 -n 'MIPS OpenWrt Linux-4.4.50' -d /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/tmp/vmlinux-wzr-hp-g300nh2.bin.lzma /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/tmp/vmlinux-wzr-hp-g300nh2.uImage
Image Name:   MIPS OpenWrt Linux-4.4.50
Created:      Thu May 18 00:10:08 2017
Image Type:   MIPS Linux Kernel Image (lzma compressed)
Data Size:    1153412 Bytes = 1126.38 kB = 1.10 MB
Load Address: 80060000
Entry Point:  80060000
if [ 0 -eq 0 ]; then filename="/var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/root.squashfs-raw"; fstype=${filename##*\.}; case "${fstype}" in *) bs=`stat -c%s /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/tmp/vmlinux-wzr-hp-g300nh2.uImage`;; esac; ( dd if=/var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/tmp/vmlinux-wzr-hp-g300nh2.uImage bs=${bs} conv=sync;  cat /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/root.squashfs-raw ) > /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin; if [ -n "64" ]; then case "${fstype}" in squashfs*) padjffs2 /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin 64; ;; esac; fi; if [ `stat -c%s /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin` -gt $((33095680-4*64*1024)) ]; then echo "Warning: /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin is too big (> $((33095680-4*64*1024)) bytes)" >&2; rm -f /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin; fi; else if [ 0 -gt 262144 ]; then if [ `stat -c%s "/var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/tmp/vmlinux-wzr-hp-g300nh2.uImage"` -gt 0 ]; then echo "Warning: /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/tmp/vmlinux-wzr-hp-g300nh2.uImage is too big (> 0 bytes)" >&2; else if [ `stat -c%s /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/root.squashfs-raw` -gt $((33095680-4*64*1024)) ]; then echo "Warning: /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/root.squashfs-raw is too big (> $((33095680-4*64*1024)) bytes)" >&2; else ( dd if=/var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/tmp/vmlinux-wzr-hp-g300nh2.uImage bs=0 conv=sync; dd if=/var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/root.squashfs-raw ) > /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin; fi; fi; else ( dd if=/var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/tmp/vmlinux-wzr-hp-g300nh2.uImage bs=0 conv=sync; dd if=/var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/root.squashfs-raw ) > /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin; if [ `stat -c%s /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin` -gt $((33095680-4*64*1024)) ]; then echo "Warning: /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin is too big (> $((33095680-4*64*1024)) bytes)" >&2; rm -f /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin; fi; fi; fi
bash: /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin: No such file or directory
[padjffs2] *** error: Unable to open /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin, No such file or directory
stat: cannot stat '/var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin': No such file or directory
bash: line 0: [: -gt: unary operator expected
if [ -e "/var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin" ]; then ( echo -n -e "# Airstation Public Fmt1\x00\x00\x00\x00\x00\x00\x00\x00"; dd if=/var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin; ) > /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-tftp.bin; buffalo-enc -p WZR-HP-G300NH2 -v 1.99 -i /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-sysupgrade.bin -o /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/tmp/wzr-hp-g300nh2.enc; buffalo-tag -b WZR-HP-G300NH2 -p WZR-HP-G300NH2 -a ath -v 1.99 -m 1.01 -l mlang8 -w 3 -c 0x80041000 -d 0x801e8000 -f 1 -r M_ -i /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/tmp/wzr-hp-g300nh2.enc -o /var/lib/buildbot/slaves/slave/ar71xx-generic/build/firmware/imgzVQ9k2/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-g300nh2-squashfs-factory.bin; fi
```

**Comment by hafu** [comment]
I can't reproduce the error above.

It seems to be an error passing the destination (BIN_DIR) for some cases. Especially if [/target/linux/ar71xx/image/legacy.mk#L133-L166 of LEDE](https://github.com/lede-project/source/blob/ac733df99c78f54b4cf9a8710f70a506f73e66fc/target/linux/ar71xx/image/legacy.mk#L133-L166) is involved the BIN_DIR is ignored/not passed through.

Here a snippet of my build log:
```shell
Image Name:   MIPS OpenWrt Linux-4.4.50                                         
Created:      Sun Jun  4 22:20:10 2017                                          
Image Type:   MIPS Linux Kernel Image (lzma compressed)                         
Data Size:    1153434 Bytes = 1126.40 kB = 1.10 MB                              
Load Address: 80060000                                                          
Entry Point:  80060000                                                          
if [ 0 -eq 0 ]; then                                                            
    filename="/home/hannes/git/freifunk/firmware/img005niX/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/root.squashfs-raw"; 
    fstype=${filename##*\.};                                                    
    case "${fstype}" in                                                         
        *)                                                                      
        bs=`stat -c%s /home/hannes/git/freifunk/firmware/img005niX/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/tmp/vmlinux-wzr-hp-ag300h.uImage`;; 
    esac;                                                                       
                                                                                
    (                                                                           
        dd if=/home/hannes/git/freifunk/firmware/img005niX/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/tmp/vmlinux-wzr-hp-ag300h.uImage bs=${bs} conv=sync;  
        cat /home/hannes/git/freifunk/firmware/img005niX/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/build_dir/target-mips_24kc_musl-1.1.16/linux-ar71xx_generic/root.squashfs-raw 
    ) > /home/hannes/git/freifunk/firmware/img005niX/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-ag300h-squashfs-sysupgrade.bin;
```

```/home/hannes/git/freifunk/firmware/img005niX/freifunk-berlin-imagebuilder-0.3.0-alpha-ar71xx-generic.Linux-x86_64/bin/targets/ar71xx/generic/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-ag300h-squashfs-sysupgrade.bin``` should be ```/home/hannes/git/freifunk/firmware/firmwares/ar71xx-generic/default/freifunk-berlin-0.3.0-alpha-cb95b17-ar71xx-generic-wzr-hp-ag300h-squashfs-sysupgrade.bin```

**Comment by SvenRoederer** [comment]
confirmed that https://github.com/freifunk-berlin/firmware/pull/434/commits/b0784dd57e01bbb240305a0a250694ff6a8d88b3 fixed the problem of imagebuilder

**Comment by SvenRoederer** [comment]
@hafu can you open an issue in the LEDE-repo for this? 
is this still present in LEDE-master?
(Damn, found this BIN_DIR thing myself and later saw that you seems to have edited your old post and already described is. - Note to myself: don't use this edit function when you loke to have notifications sent out)

@lynxis Do you see the fix on the 1st view?

**Comment by SvenRoederer** [comment]
merged in 8765a27ee5e6d6bbc9ce3e8712919c02c85fac35 .. db47a2d24e25576e3da0bbf025169ccd4acea536
the last commit taken as Hotfix till issue is solved upstream

**Pull request closed without merging**
