### PR TITLE
Makefile: run imagebuilder in parallel

### PR DESCRIPTION
**Pull request by andrenarchy**
# What does it do?

Uses make's `-j` option to parallelize imagebuilder. The changes in this PR work as follows:

* first `IB_JOB_TARGETS` is initialized with make targets for each imagebuilder run, see `ib-generate-jobs.sh`
* instead of calling `assemble_firmwares.sh` make passes the jobs to `ib-generate-firmware.makefile` which automatically parallelizes the jobs according to the `-j` flag.
* `assemble_firmwares.sh` was renamed to `ib-generate-firmware.sh` and adapted to build only a single firmware

Note: each imagebuilder run runs in an isolated imagebuilder directory so there are no race conditions (thus consuming more disk space though depending on `-j`).

# Benchmark

Timings for ar71xx-generic `make` on machine with 16 cores:

* build [265](https://buildbot.berlin.freifunk.net/builders/ar71xx-generic/builds/265) (master) takes 40 minutes
* build [267](https://buildbot.berlin.freifunk.net/builders/ar71xx-generic/builds/267) (this PR) takes 24 minutes

### CODE REVIEW

**Comment by andrenarchy** [comment]
Also note that there is an issue in imagebuilder with `BIN_DIR` that breaks some profiles (e.g., DIR505, also happens in master right now but it just seems to ignore the error instead of failing, see https://bugs.lede-project.org/index.php?do=details&task_id=590)

**Comment by SvenRoederer** [comment]
I assume this change will extract the Imagebuilder for every ib-job separately. In this case this will make issue https://github.com/freifunk-berlin/firmware/issues/414 even more relevant (esp. fir Buildslave wg1337)

**Comment by booo** [comment]
I suggest that we add a bit more documentation to the code, makefile, README and commit body.

Why don't we fix this upstream?

**Comment by andrenarchy** [comment]
Imagebuilder is designed to build one profile with one package list. Adding parallelization there would require quite some rewriting there and break the way parameters are passed. We could try to improve imagebuilder such that parallel runs in the same directory don't lead to conflicts.

I'm happy to add some documentation. :)

**Comment by booo** [comment]
> [...] break the way parameters are passed. We could try to improve imagebuilder such that parallel runs in the same directory don't lead to conflicts.

I don't understand that. Can you explain why parallel runs create conflicts? How does it break the way parameters are passed.

I agree it's work but maybe it's worth the effort.

**Comment by andrenarchy** [comment]
If we have parallel imagebuilder `make` runs they may create/remove files in the same places. Not sure I want to dive deep into the imagebuilder code to check this. Maybe @lynxis has more knowledge here?

**Comment by booo** [comment]
I patched my local LEDE based imagebuilder to accept multiple TARGET_DEVICES/PROFILEs. With this patch I can build all ar71xx devices in ~ 12s on my laptop. Calling the imagebuilder again and again for each profile causes useless fetches of the package index, download of packages and checksum calculation. We can circumvent these problems if we work on a patch that adds support for multiple TARGET_DEVICES/PROFILEs to the imagebuilder.

**Comment by andrenarchy** [comment]
@booo  :+1: 
@lynxis do you see any problems getting this upstream?

**Comment by booo** [comment]
I will try to come up with a proper patch that we can push upstream. The current implementation is a bit hacky.

**Comment by andrenarchy** [comment]
I know. :)

**Comment by booo** [comment]
The imagebuilder calls the board Makefile here:

https://github.com/lede-project/source/blob/master/target/imagebuilder/files/Makefile#L177

E.g. the Makefile for ar71xx:

https://github.com/lede-project/source/blob/master/target/linux/ar71xx/image/Makefile

If the target is e.g. generic we include for example the tp-link.mk:

https://github.com/lede-project/source/blob/master/target/linux/ar71xx/image/Makefile#L16

The tp-link Makefile adds a lot of TARGET_DEVICES to the namespace:

https://github.com/lede-project/source/blob/master/target/linux/ar71xx/image/tp-link.mk#L1027

https://github.com/lede-project/source/blob/master/include/image.mk

The board Makefile from here:

https://github.com/lede-project/source/blob/master/target/linux/ar71xx/image/Makefile#L64

calls BuildImage from the included image.mk file:

https://github.com/lede-project/source/blob/master/include/image.mk#L518

And somewhere in the BuildImage function we iterate through all the devices and build an image for each device:

https://github.com/lede-project/source/blob/master/include/image.mk#L561

If we add an option to overwrite the TARGET_DEVICES and LEGACY_DEVICES variables in the call chain we reduce the number of devices we build and speed up the build process.

**Comment by booo** [comment]
Closing this due to inactivity. Nevertheless thanks for your time and work.

I still think we should improve the image builder upstream so everybody benefits from an improved build process.

**Pull request closed without merging**
