### PR TITLE
WIP: User-friendly documentation for Freifunk Berlin Firmware

### PR DESCRIPTION
**Pull request by Akira25**
# WIP: Documentation for Freifunk Berlin
This Merge Request contains a first draft for a user friendly documentation of Freifunk Berlin Firmware. Thus it does not only contain a rather technical section for documenting the firmware component. Instead, it incorporates several sections and might be more like a handbook, than a documentation.

### Flash section:
This section is written in German. It represents all steps of setting up a Freifunk router in a rather tutorial-like style. Mostly of its contents were copied from the Freifunk Wiki. In opposite to the wiki, it aims to hold the information in a more dense matter: We can pass the tutorial for setting up a router from the start till all the end by just clicking the "Next"-buttom.
Besides minor issues like spelling this section should be fully deployable now.

### User section:
This is under construction. The idea is to give a detailed view of the LuCI-Interface and all its end-user-related functions. In this section there might be also tutorial for setting up an extension of the home-wifi on the freifunk router.

### Backbone:
Heavily under Construction. General description of building backbone-nodes in Freifunk Berlin style.

### Development:
This section is meant to hold all stuff related to firmware-development. Thus its written in English. It should have a more detailed description of the Freifunk Berlin buildsystem. I.e. where to change code to incorporate a new package, a general description of the build-process, and so forth.

### CODE REVIEW

**Comment by Akira25** [comment]
@rtznprmpftl

**Comment by SvenRoederer** [comment]
IMHO we should not add the user documentation into the firmware-build repo. 
Recently (last year) there was the agreement to do the user-documentation in the Freifunk-wiki. This was agreed on, to have a broader base of people the will keep the pages up to date.
Having this in the repo puts additional work on managing the PRs and porting commits across branches.

**Comment by sarumpaet** [comment]
What Sven says.

We just moved the documentation from the berlin.freifunk.net Git repo to the wiki. This was a success: while the documentation in Git had very few contributors and few commits, at least for a while, there were quite a lot of changes to the docs in the wiki by quite a few people.

If there are things missing in the wiki docs, please improve them. Don't start yet another construction site.

**Comment by Akira25** [comment]
Okay, I agree on the point, that in the wiki more people can edit the user-docs more seamlessly. I'd like to discuss some approaches to a better firmware-development and buildsystem documentation in this new issue.

**Pull request closed without merging**
