### PR TITLE
patches: update kernel to 4.4.205 for Hedy-1.0.x

### PR DESCRIPTION
**Pull request by SvenRoederer**
This is a patch of upstream PR https://github.com/openwrt/openwrt/pull/2633. As Lede-17.01 has been EOLd, this patch will no be accepted. 
I did it for quick and it's working on two of my ar71xx-generic boards (CPE210-v1, WR842-v3).
* CPE210: upgraded installation from previous Hedy-version, doing only AdHoc and 802.11s mesh
* WR842: fresh installed system (default-image) by the wizard

@torte71 reports problems when bringing up the AP-vif, see:
* https://github.com/freifunk-berlin/firmware/commit/87dc6b324cc6dacfea3ebaed8052e6cd0072b418#commitcomment-36497530
* console-log: https://github.com/freifunk-berlin/firmware/commit/87dc6b324cc6dacfea3ebaed8052e6cd0072b418#commitcomment-36500854

### CODE REVIEW

**Comment by SvenRoederer** [comment]
@torte71  can you test with a fresh install on your devices?
I'll try to dismount my CPE210 and test the kernel there.

**Comment by torte71** [comment]
If you refer to buildbot's nr. 90 "Hedy-1.0.x_kernel4.4.205", revision 5951156 - it still crashed in the moment that I added and enabled an 802.11s AP ("default" image for gl-ar150; updated with "sysupgrade -n"). I also checked using the wizard - crashes as well.

**Comment by SvenRoederer** [comment]
I just did a test on a CPe210 v1.1, with build 5951156. Setup from scratch by only the wizard. No problems seen for 2h when running AP and AdHoc. I manually changed the settings of the AdHoc-Mesh to 802.11s (changing type, Mesh-ID and forwarding) and it's running for 10 minutes now. there is no link to any 802.11s-peer.
``` 
root@test_4:~# cat /etc/config/wireless 

config wifi-device 'radio0'
        option type 'mac80211'
        option path 'platform/ar934x_wmac'
        option htmode 'HT20'
        option disabled '0'
        option country 'DE'
        option doth '0'
        option diversity '1'
        option channel '13'
        option hwmode '11g'

config wifi-iface
        option network 'wireless0'
        option encryption 'none'
        option device 'radio0'
        option mcast_rate '6000'
        option ifname 'wlan0-adhoc-2'
        option mode 'mesh'
        option mesh_id 'Freifunk-Berlin-Mesh'
        option mesh_fwding '0'

config wifi-iface
        option ifname 'wlan0-dhcp-2'
        option network 'dhcp'
        option encryption 'none'
        option device 'radio0'
        option mode 'ap'
        option ssid '44205.freifunk.net'
``` 
@torte71 Do you have links to 802.11s-peers active?

**Comment by torte71** [comment]
When skipping the wizard, I intentionally chose SSIDs and/or mesh-IDs, that don't exist here to avoid links to mesh partners, but it crashed as well.
Things, that I maybe doing differently than you:
- I only tested the buildbot image. Did you compile the firmware on your own?
- I always have a serial/TTL connection to the devices
- I always do the configuration (via luci) over the wan interface instead of lan
I'll try to test, if one of these points makes a difference (these days)

**Comment by torte71** [comment]
Checked with a self-compiled rev. 5951156, without serial/TTL and over the lan port: No change. Still crashes in about 9 out of 10 cases when enabling either a 802.11s or AdHoc interface.

**Comment by SvenRoederer** [comment]
* I also used the buildbot image
* Will the reboots stop, when you disconnect the serial-console? The only difference by using this port is, that the getty will be active vs. sleeping. But this should not cause th seen problem.
* There should be no difference between using the LAN or WAN port.

I'll share the config of the CPe210 that's running for me, perhaps you can try this and get different results. 
If all these crashes would only happen on one device, I would think of a potential hardware-problem, but you see this on CPe210 and AR150 ...

**Comment by SvenRoederer** [comment]
Ich hab das mal als Testaufruf auf die [Mailingliste gepackt](https://lists.berlin.freifunk.net/pipermail/berlin/2019-December/039972.html), dass ein paar zusätzliche Testreports reinkommen. 

Auf meinem GL.iNet GL-MT300N v1 probiert, und auch keine Probleme gesehen.

**Comment by SvenRoederer** [comment]
@torte71 gave a (console-log of a crash)[https://github.com/freifunk-berlin/firmware/commit/87dc6b324cc6dacfea3ebaed8052e6cd0072b418#commitcomment-36500854] he gets when running the updated kernel4.4.205, but I wonder, why the "qos" task is crashing.

**Comment by SvenRoederer** [comment]
@torte71 can you test your CPe210v1 with the following backup-file: https://www.geroedel.de/cloud/index.php/s/mkRPmioHMRwR4BA ?
This was just taken from my CPe210 v1.1 and was running for several days.

**Comment by torte71** [comment]
Tested that backup on my cpe210-v1.1 - it crashed on reboot after restoring (and kept doing so).
```
[   23.774116] br-dhcp: port 1(eth0.1) entered forwarding state
[   23.784128] br-wan: port 1(eth0.2) entered forwarding state
[   26.483850] IPv6: ADDRCONF(NETDEV_UP): wlan0-dhcp-2: link is not ready
[   26.604467] device wlan0-dhcp-2 entered promiscuous mode
[   26.633874] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0-dhcp-2: link becomes ready
[   26.641193] br-dhcp: port 2(wlan0-dhcp-2) entered forwarding state
[   26.647558] br-dhcp: port 2(wlan0-dhcp-2) entered forwarding state
[   27.208925] IPv6: ADDRCONF(NETDEV_UP): wlan0-adhoc-2: link is not ready
[   27.285784] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0-adhoc-2: link becomes ready
[   27.304335] Unhandled kernel unaligned access[#1]:
[   27.309218] CPU: 0 PID: 3 Comm: ksoftirqd/0 Not tainted 4.4.205 #0
[   27.315494] task: 83828a30 ti: 8383c000 task.ti: 8383c000
[   27.320970] $ 0   : 00000000 00000001 8037aa78 00000000
[   27.326311] $ 4   : 8383d998 00000030 27c30d57 83101028
[   27.331643] $ 8   : 00000001 00000016 00000000 00000000
[   27.336977] $12   : ff020000 00000003 00000000 00000000
[   27.342310] $16   : 8037aa79 80390000 27c30d57 82e24e00
[   27.347642] $20   : 82e24d70 83258bd0 00000000 830bb2f0
[   27.352975] $24   : 00000000 67dc6473
[   27.358307] $28   : 8383c000 8383d958 80390504 8024d010
[   27.363641] Hi    : 00139de6
[   27.366563] Lo    : 40096a83
[   27.369490] epc   : 80334ef0 0x80334ef0
[   27.373377] ra    : 8024d010 0x8024d010
[   27.377263] Status: 1100e403 KERNEL EXL IE
[   27.381533] Cause : 00800010 (ExcCode 04)
[   27.385597] BadVA : 27c30d57
[   27.388520] PrId  : 0001974c (MIPS 74Kc)
[   27.392495] Modules linked in: ifb iptable_nat ath9k nf_nat_ipv4 nf_conntrack_ipv6 nf_conntrack_ipv4 ipt_REJECT ipt_MASQUERADE ath9k_common xt_time xt_tcpudp xt_tcpmss xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_HL xt_DSCP xt_CLASSIFY nf_reject_ipv4 nf_nat_redirect nf_nat_masquerade_ipv4 nf_nat nf_log_ipv4 nf_defrag_ipv6 nf_defrag_ipv4 nf_conntrack_rtcache mac80211 iptable_mangle iptable_filter ipt_ECN ip_tables ath9k_hw ath act_connmark nf_conntrack act_skbedit act_mirred em_u32 cls_u32 cls_tcindex cls_flow cls_route cls_fw sch_tbf sch_htb sch_hfsc sch_ingress batman_adv libcrc32c cfg80211 compat ip6t_REJECT nf_reject_ipv6 nf_log_ipv6 nf_log_common ip6table_mangle ip6table_filter ip6_tables x_tables ipip tunnel4 ip_tunnel veth gpio_button_hotplug crc16 crc32c_generic crypto_hash [last unloaded: ifb]
[   27.479781] Process ksoftirqd/0 (pid: 3, threadinfo=8383c000, task=83828a30, tls=00000000)
[   27.488160] Stack : 8037aa79 80390000 27c30d57 82e24e00 82e24d70 83258bd0 8383d9d4 00000000
          82e3b620 00000000 00000000 00000000 00000000 00000004 00580003 00000000
          86dd3a00 00000000 00000000 00000000 00000000 00000000 00000000 00000000
          ff020000 00000000 00000000 00000016 00000000 67dc6473 82e24d70 83258bd0
          82e3b600 8332a7d0 83258b40 83258b40 82e3b600 82e24e00 82e24d70 83258b40
          ...
[   27.524486] Call Trace:[<8332a7d0>] 0x8332a7d0 [mac80211@83300000+0x60740]
[   27.531541] [<8332ab34>] 0x8332ab34 [mac80211@83300000+0x60740]
[   27.537558] [<8332831c>] 0x8332831c [mac80211@83300000+0x60740]
[   27.543575] [<8332c83c>] 0x8332c83c [mac80211@83300000+0x60740]
[   27.549595] [<8332db7c>] 0x8332db7c [mac80211@83300000+0x60740]
[   27.555597] [<800f81d4>] 0x800f81d4
[   27.559139] [<8009b778>] 0x8009b778
[   27.562673] [<800a18c0>] 0x800a18c0
[   27.566215] [<800f81d4>] 0x800f81d4
[   27.569758] [<800a1d48>] 0x800a1d48
[   27.573296] [<800f832c>] 0x800f832c
[   27.576832] [<8023ec78>] 0x8023ec78
[   27.580392] [<8332de80>] 0x8332de80 [mac80211@83300000+0x60740]
[   27.586408] [<8025454c>] 0x8025454c
[   27.589953] [<80254640>] 0x80254640
[   27.593499] [<80254b1c>] 0x80254b1c
[   27.597040] [<8025ecd4>] 0x8025ecd4
[   27.600576] [<8025fadc>] 0x8025fadc
[   27.604117] [<802daa5c>] 0x802daa5c
[   27.607663] [<8027feec>] 0x8027feec
[   27.611211] [<802dd93c>] 0x802dd93c
[   27.614752] [<8027feec>] 0x8027feec
[   27.618290] [<802dd770>] 0x802dd770
[   27.621827] [<802fc44c>] 0x802fc44c
[   27.625370] [<80289158>] 0x80289158
[   27.628921] [<802fdbd8>] 0x802fdbd8
[   27.632457] [<802fdc0c>] 0x802fdc0c
[   27.636004] [<800929f4>] 0x800929f4
[   27.639541] [<802fd9a8>] 0x802fd9a8
[   27.643079] [<800aea38>] 0x800aea38
[   27.646618] [<800aecb4>] 0x800aecb4
[   27.650153] [<800ad368>] 0x800ad368
[   27.653693] [<80083b8c>] 0x80083b8c
[   27.657229] [<8009b47c>] 0x8009b47c
[   27.660770] [<80083bfc>] 0x80083bfc
[   27.664305] [<8009a390>] 0x8009a390
[   27.667842] [<8009a4e4>] 0x8009a4e4
[   27.671379] [<8009a390>] 0x8009a390
[   27.674916] [<8006712c>] 0x8006712c
[   27.678455] [<8009a390>] 0x8009a390
[   27.681992] [<800982f8>] 0x800982f8
[   27.685532] [<80098220>] 0x80098220
[   27.689067] [<80060878>] 0x80060878
[   27.692609]
[   27.694115]
Code: afb3000c  afb20008  afb00000 <8cc20000> 3c116c79  3c0f736f  26316765  25ef6d65  8cd80008
[   27.704330] ---[ end trace 78efe60ed8965936 ]---
[   27.711352] Kernel panic - not syncing: Fatal exception in interrupt
[   27.718894] Rebooting in 3 seconds..
```

**Comment by torte71** [comment]
If I leave it rebooting long enough, then it will reach a stable, working state, once in a while (maybe in 1 out of 10 reboots). In this (rare) state, the device works as expected, e.g. it meshes fine with another box (after adjusting the mesh-id, mine is different for reasons). No instabilities seen in this state, e.g. when reconfiguring the wifi settings (until next reboot).
Smells like a timing/initializiation issue in the kernel to me.

**Comment by SvenRoederer** [comment]
By now, there are some nodes seem to run stable see following statistics taken from hopglass. Neighter in thus issue nor the mailinglist are additional problems reported than by @torte71 .

I strongly think of changing to this kernel officially an mention this problem seen by @torte71 as possible issue.

Hedy_kernel4 4 205

Any comments on this idea?

**Comment by booo** [comment]
Why should we update the kernel?

**Comment by SvenRoederer** [comment]
Usually new kernel-versions get release to fix errors and security-problems.

**Comment by pmelange** [comment]
What, in the kernel changelog, is the reason for a new kernel version?

I ask, because I scanned over the changelogs on kernel.org and didn't see anything that jumped out at me as obvious and needed for openwrt/freifunk.

**Comment by SvenRoederer** [comment]
As mentioned, I had this patch ready by random / by other reason. As upstream has EOLd 17.01 I'm asking if we want to apply on our firmware.
I even can drop it to the void.

I even don't know if this change will fix a known or unknown security-issue,

**Comment by SvenRoederer** [comment]
My intention is to merge this PR, and make a Hedy-1.0.5 afterwards. There is only @torte71 reporting this problem. If finally more users see failures, we can always revert this commit and release a Hedy-1.0.6.

**Comment by SvenRoederer** [comment]
added to Hedy-1.0.x branch in 3d64405ad3ce0f0c145a040edd427f040f3f3a17

**Pull request closed without merging**
