### PR TITLE
add changes for release 0.1.0 to CHANGELOG.md

### PR DESCRIPTION
**Pull request by booo**
I suggest we push a release as soon as possible. This is a draft for the changelog.

### CODE REVIEW

**Comment by andrenarchy** [comment]
I suggest to first review the pending PRs: #192 #171 #149

**Comment by booo** [comment]
#192 contains a lot of changes we can't test right now.
#171 works for me but contains changes that are more or less not relevant to us
#149 we should just close this as there is no activity and we don't own target hardware

**Comment by booo** [comment]
Apart form some additions do you have any comments on this. What does our changelog master (@geirkairam) say?

**Comment by booo** [comment]
Another take on the changelog:

```
CHANGELOG.md: fix version number (a309bbf)
Fix markdown for CHANGELOG.md (9b0693b)
README: add ipv6 resolvers to feature list (811566d)
Update OpenWrt revision to 43770. (337b6e8)
[configs] build tcpdump as optional package (5d6b47a)
[configs]: build ath{5,9,10}k wifi drivers as modules for x86 target (5dab54c)
[configs]: increase VERSION_NUMBER to 0.1.0 (baeed92)
[feeds] change url for packages berlin to new repo url (dbf79a8)
[feeds] update feeds to include vpn03-firewall fix (a72f5de)
[feeds] update packages_berlin feed (fc2e535, 8b524d0)
[patches] add two ipv6 nameservers (83df6ab)
[patches] backport support for ubnt loco xw (7142d00)
[patches] fix regression introduced by openvpn update in openwrt release (08762ad)
[patches] remove dead code and add a comment to firstboot redirect patch (afaef84)
[patches] remove unused regdb.txt patch (ec39bf0)
add support for TL-WR710N (6ac7e57)
build and integrate freifunk-berlin-migration package into firmware (55b9fe5)
fix multiple policyrouting rules (9a72280)
fix policyrouting typo (208aada)
patches: change default dhcp leasetime to 5 minutes (b38af12)
patches: fix ascii art in /etc/banner (99a4382, 9c8394c)
patches: fix redirect on firstboot (8dc3728)
remove 4MB constraint from mikrotik profile (74e8316)
update openwrt/packages to head of branch for-14.07 (9b2c15c)
```

**Pull request closed without merging**
