### PR TITLE
embedded_files: add freifunk favicon to embedded_files

### LINKED ISSUE #791: Enhancement: Use the freifunk favicon.png for the luci interface
I recommend using the freifunk favicon for the web interface. 

favicon

To do this, I would recommend putting this into the $OPENWRT_DIR/files/www/luci-static/bootstrap folder to overwrite the original.

Screenshot_2020-04-29_12-17-33

Original size: 733 bytes
Freifunk site:1528 bytes (possibly this can be optimized).

### PR DESCRIPTION
**Pull request by pmelange**
This overwrites the existing openwrt favicon with the freifunk favicon.

Compiled and tested on a WDR3600.  The favicon come up as expected.

Fixes #791 

Signed-off-by: pmelange <isprotejesvalkata@gmail.com>

### CODE REVIEW

**Comment by booo** [comment]
Can you please check if we can serve a SVG instead of a PNG?

**Comment by pmelange** [comment]
It would also work with a SVG, but in order to do that we would need to modify/patch https://github.com/openwrt/luci/blob/81effc111227bc65cb974829f17a45515fbe9807/themes/luci-theme-bootstrap/luasrc/view/themes/bootstrap/header.htm#L29

**Comment by pmelange** [comment]
As an extra bonus, I tried renaming the SVG to favicon.png to see if it works.  Nope.  Instead no favicon is displayed.

**Comment by SvenRoederer** [comment]
As we spoke on modifying the page-footer, to include a dedication-note (#747) I suggest to use a LuCI-theme for this. Both changes can be added on a clean and standard way, which IMHO is much better than hacking this via "embedded_files".

Similar had been done in "officially" in LuCI (before some packages have been moved to the freifunk-repo (https://github.com/freifunk/openwrt-packages/tree/ac16b4a424b5761950a7b8d7fd7b439fe334e58d/themes/luci-theme-freifunk-generic).

**Comment by pmelange** [comment]
> better than hacking this via "embedded_files".

I do not agree that this is a hack, as it is a documented and support way to customize an installation: https://downloads.openwrt.org/releases/18.06.4/targets/ar71xx/generic/openwrt-18.06.4-ar71xx-generic-ubnt-unifiac-mesh-squashfs-sysupgrade.bin

If/when a desired theme has been created, then this commit could be reverted.

Otherwise, please just NACK and close this PR.

**Comment by pmelange** [comment]
Oops, copied the wrong link into the text.  I have updated the comment.

https://openwrt.org/docs/guide-developer/build-system/use-buildsystem#custom_files

**Comment by SvenRoederer** [comment]
Please check the new Freifunk-generic-theme (https://github.com/freifunk/openwrt-packages/pull/30)

**Comment by SvenRoederer** [comment]
the favicon of this branch has been integrated into freifunk/openwrt-packages#30

**Comment by SvenRoederer** [comment]
Another drawback of using embedded_files for this: it will only work for the specific theme "bootstrap" and not for others.

**Pull request closed without merging**
