### PR TITLE
Hedy-1.0.x: add wndr3700v2

### PR DESCRIPTION
**Pull request by pmelange**
Adds support for hardware device WNDR3700v2

### CODE REVIEW

**Comment by SvenRoederer** [comment]
I don't really like the idea of supporting a new board for ar71xx. OpenWrt will go to ath79 and every ar71xx-board has the potential to cause additional swiitch-target-hassle.
I suggest to leave it for the user, to build an image for this board on Hedy-1.0.x. It's a quit simple task with the imagebuilder and only takes 5 minutes.

**Comment by xa-y-ax** [comment]
Unfortunately the imagebuilder throws some errors:
Collected errors:
 * opkg_install_cmd: Cannot install package kmod-leds-wndr3700-usb.
Makefile:150: recipe for target 'package_install' failed
make[3]: *** [package_install] Error 255
Makefile:110: recipe for target '_call_image' failed
make[2]: *** [_call_image] Error 2
Makefile:206: recipe for target 'image' failed
make[1]: *** [image] Error 2
make[1]: Leaving directory
'/home/xayax/firmware/imgNT0enz/freifunk-berlin-imagebuilder-1.0.4-ar71xx-generic.Linux-x86_64'
Makefile:204: recipe for target '.stamp-images' failed
make: *** [.stamp-images] Error 2

so it seems to take more than 5 minutes ;) 
i think every change has the potential to make something really *** ? - but let's try. so we can use the donated routers...

**Comment by SvenRoederer** [comment]
Thanks for testing ... a missing hardware-driver ...

A compromise between my initial comment / concern and this dependency-error is to enable the required hardware-driver or all kernel-modules (as we do on master)

**Comment by Akira25** [comment]
Could we at least provide a step-by-step manual for that in the wiki? I
would write it by myself, but need a overall view over the steps to be
taken.

Am 26.11.19 um 21:48 schrieb Sven Roederer:

**Comment by SvenRoederer** [comment]
@Akira25 as mentioned in #736 it's already in the readme: https://github.com/freifunk-berlin/firmware#customizing-make

**Comment by SvenRoederer** [comment]
In PR #740 is the backport of "CONFIG_TARGET_ALL_PROFILES" which enable all hardware-relevant packages in the imagebuilder. So we can provide support for interested users for the Netgear WDNR3700 without officially supporting it. 
The official support should be introduced in the next major release and starting with ath79-target.

**Comment by SvenRoederer** [comment]
I just checked the hopglass statistics; There are 2 users of this hardware. One is running Hedy-1.0.2, the other some development-branch based on OpenWrt-19.07. Both nodes seem not to be run by "I want this as an Enduser-release" nodeoperators.
So I'll close this PR as we have the inofficial support by providing all packages to create an image via Imagebuilder and official support in master branch.

**Pull request closed without merging**
