### PR TITLE
Update to the Luci feed master branch

### PR DESCRIPTION
**Pull request by pmelange**
Included are changes to the patches we use.

### CODE REVIEW

**Comment by pmelange** [comment]
seeissue #609

**Comment by SvenRoederer** [comment]
switching to Luci-master should in turn cause switching OpenWrt and the other feeds to master. This will lead to https://github.com/freifunk-berlin/firmware/issues/583

**Comment by pmelange** [comment]
Yes, this should be merged in the future (maybe January).  When there is a 19.x fork, this PR could come in handy.

Maybe we should keep an upstream_master branch for proactive changes to the upstream code

**Comment by SvenRoederer** [comment]
> Maybe we should keep an upstream_master branch for proactive changes to the upstream code

I made some scripts, which automatically updating branch "daily/upstream-master" to the recent changes of the master-branches we rely on.
So we can collect such "cutting edge changes" there.

As of this, I close this one here

**Pull request closed without merging**
