### PR TITLE
fix out of tree build + speed up build

### PR DESCRIPTION
**Pull request by lynxis**

### CODE REVIEW

**Comment by andrenarchy** [comment]
Why carambola2? Is this just any device so it doesn't build all the images in the `compile` target because the actual images are created within the `firmwares` target?

**Comment by lynxis** [comment]
I like the carambola2 ;). But it doesn't matter which one, but most targets are multiboard targets.
> Is this just any device so it doesn't build all the images in the compile target because the actual images are created within the firmwares target?
Correct.

**Comment by andrenarchy** [comment]
Alright. :smiley: I pushed the branch to this repo so the buildbot is triggered: https://github.com/freifunk-berlin/firmware/tree/lynxis/fastbuild

**Comment by lynxis** [comment]
It works, but the imagebuilder is now missing some packages.
E.g. ohci package is missing for some profiles, because the carambola2 doesnt depend on that.
Also the imagebuilder doesn't fail. See #228.

**Comment by cholin** [comment]
What is the status of this PR? Seems we need the `default` target, don't we?

**Comment by lynxis** [comment]
no. It's missing some package, but still saves some time.

**Comment by lynxis** [comment]
rebase against freifunk/master

**Comment by lynxis** [comment]
Buildbot build was successful. See http://buildbot.berlin.freifunk.net/builders/ar71xx/builds/547

**Comment by andrenarchy** [comment]
Thx @lynxis, merging in a minute...

**Pull request merged**
