### PR TITLE
Update README.md according to #209

### PR DESCRIPTION
**Pull request by research7**
More info about the development process and some prerequisites.

### CODE REVIEW

**Comment by research7** [comment]
accidental closing reversed ;-)

**Comment by booo** [comment]
I changed your commit a little bit. Please take a look and let me know what you (@research7) think:

https://github.com/freifunk-berlin/firmware/tree/research7-master

**Comment by research7** [comment]
All changes are fine. Especially the build-options link you included will be very useful for future contributors.
Thanks.

**Comment by booo** [comment]
Closed with https://github.com/freifunk-berlin/firmware/commit/cba0a89a9bb97c14f977e750bf6019afa224e182

**Pull request closed without merging**
