### PR TITLE
Update/feed routing for new olsr version

### PR DESCRIPTION
**Pull request by andrenarchy**
The commits in this PR update the routing feed which includes the most recent olsr release 0.6.8. Furthermore, the olsrd PingCmd patch is removed since it is now included in the upstream release.

The remaining commits in the routing feed shouldn't affect the firmware but the new olsrd release includes a bunch of commits dedicated to smartgateways so we should test this before merging the PR.

### CODE REVIEW

**Comment by booo** [comment]
I spotted this in the log after a restart:
```
olsrd: /etc/init.d/olsrd: warning_invalid_value() in option 'olsrd.cfg0c4e54.PingCmd', skipped
```

**Comment by booo** [comment]
We should push this change upstream: https://github.com/freifunk-berlin/firmware/commit/82a09a2f4480647b9dd51c0085d7e89fa44641ac#diff-fbb01f684d9bef30d1275d2e46707d0eL115

**Comment by andrenarchy** [comment]
Oh, I didn't realize that the patch affects 2 repositories. So the `olsrd.init` patch needs to be pushed upstream to https://github.com/openwrt-routing/packages. I'll take care of this.

**Comment by booo** [comment]
@andrenarchy Can you fix the series file too?

**Comment by andrenarchy** [comment]
The `olsrd.init` patch is now pending in openwrt-routing/packages#75.

@booo: the series file is now updated.

**Comment by andrenarchy** [comment]
openwrt-routing/packages#75 has been merged and the feeds.conf has been updated in this PR.

@booo: can you test this again? Buildbot is compiling the branch [here](http://buildbot.berlin.freifunk.net/builders/ar71xx/builds/442).

**Comment by booo** [comment]
I can give it a try but you should test too.

I expect to see a lot of log messages like this on a WDR4900:
```
Sat Jan  3 00:59:16 2015 daemon.err olsrd[10071]: OLSR: sendto IPv4 Operation not permitted
Sat Jan  3 00:59:17 2015 daemon.err olsrd[10071]: OLSR: sendto IPv4 Operation not permitted
Sat Jan  3 00:59:18 2015 daemon.err olsrd[10071]: OLSR: sendto IPv4 Operation not permitted
Sat Jan  3 00:59:18 2015 daemon.err olsrd[10071]: OLSR: sendto IPv4 Operation not permitted
```

**Comment by andrenarchy** [comment]
I only have a TL-WR703N here (which we do not support due to 4MB flash). I can test it on WDR3600 tonight.

**Comment by booo** [comment]
Rebased this on the current master. Please test again.

**Comment by andrenarchy** [comment]
@booo: have you tested the build? If not: drop a line and I'll check tonight.

**Comment by booo** [comment]
Not really sorry. I can test this week too. We should release at the end of the fucking week!

**Comment by booo** [comment]
Can someone else please test these changes and merge? I do not have time for proper testing :/

**Comment by andrenarchy** [comment]
Works nicely on ar71xx (TL-WDR3600 and NanoStation M5 loco). Fixes #190.

@booo, @cholin: please merge if you want.

**Comment by andrenarchy** [comment]
Now rebased. Please merge *now*! :smiley:

**Comment by cholin** [comment]
Looks awesome!

**Pull request merged**
