### PR TITLE
Update OpenWRT to r43215

### PR DESCRIPTION
**Pull request by cholin**
Patch '006-target-imagebuilder-remove-initramfs-dep.patch' is not needed
anymore because it is already included upstream.

### CODE REVIEW

**Comment by booo** [comment]
On mpc85xx aka WDR4900 I have problems with the cipher none option of openvpn:

```
Fri Jan  2 15:29:43 2015 daemon.notice openvpn(ffvpn)[7115]: OpenVPN 2.3.6 powerpc-openwrt-linux-gnu [SSL (PolarSSL)] [LZO] [EPOLL] [IPv6] built on Dec 24 2014
Fri Jan  2 15:29:43 2015 daemon.notice openvpn(ffvpn)[7115]: library versions: PolarSSL 1.3.8, LZO 2.08
Fri Jan  2 15:29:43 2015 daemon.warn openvpn(ffvpn)[7115]: NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Fri Jan  2 15:29:43 2015 daemon.warn openvpn(ffvpn)[7115]: WARNING: file '/etc/openvpn/freifunk_client.key' is group or others accessible
Fri Jan  2 15:29:43 2015 daemon.warn openvpn(ffvpn)[7115]: ******* WARNING *******: null cipher specified, no encryption will be used
Fri Jan  2 15:29:43 2015 daemon.err openvpn(ffvpn)[7115]: Assertion failed at crypto_polarssl.c:415
Fri Jan  2 15:29:43 2015 daemon.notice openvpn(ffvpn)[7115]: Exiting due to fatal error
```
Openvpn ticket: https://community.openvpn.net/openvpn/ticket/473

@sven-ola do you know the state of the openwrt openvpn package?

**Comment by booo** [comment]
Commit that breaks openvpn: http://git.openwrt.org/?p=14.07/openwrt.git;a=commit;h=678b8b53a3a79da8f0a7ee5da8f3918cbc00ac78

**Comment by sven-ola** [comment]
Hey,

OpenWrt zieht die offizielle 2.3.6, wo
https://community.openvpn.net/openvpn/raw-attachment/ticket/473/0001-Really-fix-cipher-none.patch
noch nicht drin ist.

sven-ola@charon:/tmp/openvpn-2.3.6$ patch -p1 --dry-run < ../0001-Really-fix-cipher-none.patch 
patching file src/openvpn/crypto_backend.h
patching file tests/t_lpback.sh

Nächste Version (2.3.7?) nehme ich an.

// Sven-Ola

Am 02.01.2015 um 15:37 schrieb Philipp Borgers:

**Comment by booo** [comment]
Ich versuch mal eine Patch in die Firmware einzubauen. Stay tuned.

**Comment by booo** [comment]
Patch works for me.

Next problem are a lot of these messages:
```
Sat Jan  3 00:59:16 2015 daemon.err olsrd[10071]: OLSR: sendto IPv4 Operation not permitted
Sat Jan  3 00:59:17 2015 daemon.err olsrd[10071]: OLSR: sendto IPv4 Operation not permitted
Sat Jan  3 00:59:18 2015 daemon.err olsrd[10071]: OLSR: sendto IPv4 Operation not permitted
Sat Jan  3 00:59:18 2015 daemon.err olsrd[10071]: OLSR: sendto IPv4 Operation not permitted
```

**Comment by andrenarchy** [comment]
The olsrd messages are probably unrelated to the openvpn update+fix. I've seen these messages many times before but I don't know what's causing them. Maybe some firewall or policyrouting rules?

**Comment by booo** [comment]
Yes, they are unrelated to the openvpn update+fix but maybe related to the openwrt update or the olsrd update. I will try to look into this.

**Comment by booo** [comment]
Not sure if this is related to the openwrt update but sometimes I see this in the log on WDR4900:
```
Tue Jan  6 19:55:38 2015 kern.info kernel: [  107.816494] NETDEV WATCHDOG: eth0 (fsl-gianfar): transmit queue 6 timed out
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.823529] ------------[ cut here ]------------
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.828138] WARNING: at net/sched/sch_generic.c:255
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.833005] Modules linked in: ath9k ath9k_common iptable_nat ath9k_hw ath nf_nat_ipv4 nf_conntrack_ipv4 mac80211 ipt_MASQUERADE cfg80211 xt_time xt_tcpudp xt_tcpmss xt_string xt_statistic xt_state xt_recent xt_nat xt_multiport xt_mark xt_mac xt_limit xt_length xt_id xt_hl xt_helper xt_ecn xt_dscp xt_conntrack xt_connmark xt_connlimit xt_connbytes xt_comment xt_TCPMSS xt_REDIRECT xt_LOG xt_HL xt_DSCP xt_CT xt_CLASSIFY ts_kmp ts_fsm ts_bm nf_nat_irc nf_nat_ftp nTue Jan  6 19:55:38 2015 kern.warn kernel: [  107.925351] CPU: 0 PID: 0 Comm: swapper Not tainted 3.10.49 #1
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.931176] task: c02c22e0 ti: c7ff2000 task.ti: c02d6000
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.936567] NIP: c01cabc0 LR: c01cabc0 CTR: c0162634
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.941523] REGS: c7ff3e70 TRAP: 0700   Not tainted  (3.10.49)
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.947344] MSR: 00029000 <CE,EE,ME>  CR: 44042082  XER: 20000000
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.953440] 
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.953440] GPR00: c01cabc0 c7ff3f20 c02c22e0 0000003f c901c501 c02d0000 c02c6174 c02c8b3c 
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.953440] GPR08: 00000000 00000007 00000004 00000105 00000000 00000000 00000000 00000004 
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.953440] GPR16: 00000001 c0262294 c02c63e4 00200000 ffff4453 c03010b4 00000052 c0301fd0 
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.953440] GPR24: c0301dd0 c0301bd0 c03019d0 c02c7164 c02d0000 c02c0000 00000006 c781b000 
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.983139] Call Trace:
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.985578] [c7ff3f20] [c01cabc0] 0xc01cabc0 (unreliable)
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.990969] [c7ff3f40] [c002db68] 0xc002db68
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.995230] [c7ff3f60] [c002dd24] 0xc002dd24
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  107.999493] [c7ff3fa0] [c00283e4] 0xc00283e4
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.003754] [c7ff3ff0] [c000b2a0] 0xc000b2a0
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.008015] [c02d7e70] [c00042f4] 0xc00042f4
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.012277] [c02d7e90] [c0028598] 0xc0028598
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.016538] [c02d7ea0] [c0007da8] 0xc0007da8
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.020800] [c02d7ec0] [c000c8c4] 0xc000c8c4
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.025062] --- Exception: 901 at 0xc00072a4
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.025062]     LR = 0xc00072a4
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.032450] [c02d7f80] [c005f61c] 0xc005f61c (unreliable)
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.037842] [c02d7f90] [c004b9f8] 0xc004b9f8
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.042103] [c02d7fc0] [c02a0790] 0xc02a0790
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.046365] [c02d7ff0] [c00003c0] 0xc00003c0
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.050624] Instruction dump:
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.053583] 39080074 4200ffac 4800004c 7fe3fb78 4bfeaf55 7fe4fb78 7c651b78 3c60c028 
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.061334] 7fc6f378 3863b0c0 4cc63182 4807b175 <0fe00000> 39200001 993c3fc6 813f00e8 
Tue Jan  6 19:55:38 2015 kern.warn kernel: [  108.069258] ---[ end trace 63965e4ba458a9d2 ]---
```

**Comment by booo** [comment]
I just rebased this on the current master. Please test again.

**Comment by andrenarchy** [comment]
@booo the log message looks familiar, see https://forum.openwrt.org/viewtopic.php?pid=226003#p226003. Bluse wrote a patch which was applied in https://dev.openwrt.org/changeset/39692. The patch is still in [current barrier breaker](https://dev.openwrt.org/browser/branches/barrier_breaker/target/linux/mpc85xx/patches-3.10/220-fix_gianfar_reported_number_of_sent_bytes_to_BQL.patch) so I don't know what's going on here... ;)

**Comment by booo** [comment]
Merged after successful testing with WDR4900.

**Pull request merged**
