### PR TITLE
[feeds] update luci feed revision to latest master

### PR DESCRIPTION
**Pull request by booo**
I suggest we use the master branch instead of "stable" release branches.

Includes changes on:

53d767d luci-app-statistics: Adjust ping graphs to show target hosts separately
dccf485 luci-app-statistics: improve scaling of the associated stations graph
2a9b210 Merge pull request #522 from LuttyYang/master
1328b89 luci-theme-material: fix some style bugs
a19f97f Merge pull request #521 from LuttyYang/master
8f97c6c Revert "luci-theme-material: do not infer login state from url (#520)"
8296a47 luci-theme-material: try find current position by using lua code
9098b20 luci-theme-material: Synchronized to the LUCI version f9e590a
f9e590a luci-theme-material: do not infer login state from url (#520)
6c4341e luci-mod-admin-full: fix invalid markup in packages.htm (#518)
94ab57f luci-mod-admin-full: restructure and fix backup, restore and sysuprade (#517)
d32c685 luci-base: dispatcher expose test_post_security()
79383f5 luci-base: ensure that base url is emitted with trailing slash
b4d62d3 luci-mod-admin-full: do not access dispatcher.context.urltoken in logout
86326e0 luci-base: remove security token from urls
f23f7b8 luci-app-upnp: protect lease delete call with csrf token
c1278f9 luci-app-splash: protect admin status call with csrf token
ac34dfa luci-app-radicale: protect start/stop actions with csrf token
ae9fb03 luci-app-privoxy: protect start/stop actions with csrf token
0f1f514 luci-app-ocserv: protect disconnect action with csrf token
b9ed03c luci-app-ddns: protect start/stop actions with csrf token
d466675 luci-mod-admin-full: protect iptables counter reset and restart with token
8bb749e luci-mod-admin-full: protect network post actions with csrf tokens
6b3f804 luci-base: filter invalid opkg status lines
b5826f1 luci-mod-admin-full: protect clock, flash and opkg ops with submit token
562c47e luci-base: generalize post security token handling
e8349fb Merge pull request #513 from LuttyYang/master
780778e luci-theme-material: PR from Version 0.2.11
7b00a4a i18n: Sync translations
c8392ba luci-base: update i18n base template
1d37c9c luci.mk: correct SK language name to Slovak
d1da535 luci-app-ddns: fix typo in previous commit
2cfd11b Timezone information: update to 2015g
49a7c5b luci-app-ddns: remove title <a> hacks
2222845 Merge pull request #505 from roger-/dump1090-latlon
9eda858 dump1090: lat/lon should be floats
bd504f5 luci-base: prevent UCI changes in CBI if form is not in submit state
281d2f6 Globally replace luci.dispatcher.build_url(...) with url(...) invocations
49a2cb5 luci-base: expose luci.dispatcher.build_url() as url() in templates
3f29078 luci-base: protect simpleforms with CSRF tokens
38a9993 luci-mod-admin-full: switch to POST action for reboot
ada4a0e luci-base: switch to POST action for service reload
e440144 luci-mod-admin-full: switch to POST actions for UCI changes
9b75d8e luci-theme-bootstrap: add redir parameter to uci change menu
36f133f luci-theme-material: add redir parameter to uci change menu
8d46c20 luci-base: protect CBI forms with CSRF tokens
5a63821 luci-base: add support for POST-only actions with CSRF token check
d0f15d9 Merge pull request #503 from LuttyYang/master
7567f2d luci-theme-material: fix some style bug in LUCI newest version
5e9da82 Globally convert headline anchors into name attributes.
8023fb9 Merge pull request #501 from LuttyYang/master
78c61d6 luci-app-statistics: reorder interface, netlink and openvpn datasources
c8c4a34 luci-app-statistics: add support for sorting RRD data sources
3289e13 luci-app-statistics: add initial support for collectd-mod-openvpn
a5ae384 luci-theme-material: PR from version 0.2.6
cff2b99 luci-app-statistics: add initial support for collect-mod-sensors
56deb7b Merge pull request #488 from hnyman/black-flash
527ad73 Merge pull request #489 from hnyman/remove-bno-theme
03a90f1 luci-mod-admin-full: status: survive broken DSL status output
c10a738 luci-app-statistics: improve diagram generation, add missing title
96b031b luci-app-statistics: rework graph label handling
59d2f60 luci-app-statistics: only render index view for more than one instance
ecd460f proto_map: fix ealen range
8030cc6 Merge pull request #496 from neheb/master
2cbe5d2 resources/icons: Use ZopfliPNG to save 5.4 KB
b6fe9a7 luci-base: change index.html to be more like current themes
60e2148 themes: remove freifunk-bno theme
e759b49 Merge pull request #497 from cshore/asterisk-update
0e2c555 CONTRIBUTING.md: Add advice on pull requests
91220da applications/asterisk: Remove incorrect dependency
9e3d73f Merge pull request #495 from openwrt-es/dump1090-next
8d7a8ce applications/luci-dump1090: update config to latest version
d73db0d Merge pull request #491 from hnyman/reorganise-stats-menu
db6e228 Merge pull request #492 from ollie27/nohosts
0857aaa luci-mod-admin-full: fix dnsmasq no-hosts/addn-hosts options
da5b251 luci-app-statistics: reorganise menu items
64bfe90 Merge pull request #487 from jorgifumi/patch-1
7a04dc2 Update multiwan.po
990c2e2 Merge pull request #484 from LuttyYang/master
a60184d Merge pull request #485 from dwmw2/master
41ec4c6 luci/statistics: Fix nut UPS graphs
5a0c3bb luci-theme-material: add button select input theme
13f3ad9 Merge pull request #482 from LuttyYang/master
fea55f7 luci-theme-material: add some new features and fix some bugs
1209ab6 luci-base: set default mediaurlbase to bootstrap (current default theme)
43b2221 Merge pull request #481 from LuttyYang/master
cf0623f luci-theme-material: fix font size bug
c91a5eb luci-mod-admin-full: opkg config / prevent word-wrap
e04e263 luci-theme-material: fix Polish text longer bug
2237aab luci-theme-material: fix some bug
e82a9da Merge pull request #480 from obsy/master
b699b55 i18n/polish/base: changing form of the word
4e2f87e i18n/polish/base: truncate strings to better fit in view
dd87783 i18n/polish/firewall: typo
4b69adf Merge pull request #479 from LuttyYang/master
6c1a2e3 luci-theme-material: fix no password set, Luci displays information is illegible.
7ead90b Merge pull request #470 from thesabbir/patch-01
892dd73 Merge pull request #473 from ekaitz-zarraga/fix-luci-failsafe
c207016 Merge pull request #478 from LuttyYang/master
c332c66 Material is a clean HTML5 theme for LuCI. It is based on luci-theme-bootstrap and MUI
edc5833 luci-app-firewall: use maxlength datatype instead of validate function
f3f0de3 documentation: delete obsoleted file that has a troublesome name
cdf3122 fix path error
97d3497 fix path error
b825a14 init Material Design theme
3288fe7 Luci opkg/packages: Show package size in list of available packages
7347cf0 Merge pull request #475 from hnyman/opkg-feed-config
a42c0bb luci-mod-admin-full: restore opkg feed config capability
a16654b modules/luci-mod-failsafe: Fix nil file descriptor error
428d97e Merge pull request #471 from freifunk-berlin/remove_bno
6e1a089 community-profiles: remove bno profile
fff7c6c modules/luci-mod-rpc: fix attempt to index global 'luci' (a nil value)
f0083ab statistics: fix typo
5735cde contrib: remove obsolete luasrcdiet packaging, its built as part of luci-base now
ac65bb2 contrib: remove obsolete uhttpd packaging
62b203d contrib: remove obsolete host uci configurations
16b63cb Remove obsolete toplevel Makefile
6c72dec build/makedocs.sh: handle relative output directories
b96d223 Merge pull request #463 from hnyman/max-len-version
ca75918 Luci opkg/packages: Limit version string display to 26 chars
daeb201 luci-lib-ip: fix documentation issue
3d0e8de Regenerate api documentation
00e2b03 Move doc/ to documentation/api/
ed1a641 Fix module lines in several luadoc files
8084bab luci.utils.contains: update documentation to match reality
2e61188 Add generated documentation to repository
fdb7daa Merge pull request #460 from jplitza/master
60f62f8 Merge pull request #416 from fabio70mi/patch-1
90c841d luci-lib-jsonc: Fix memory leak in stringify()
c0e2255 Merge pull request #393 from nmav/no-group-match
a36a73c Merge pull request #457 from jplitza/master
e7645d5 luci-lib-jsonc: allow encoding empty lists
e32a877 luci-lib-jsonc: Ignore non-string-or-number keys in tables
0d5070c statistics: remove references to Lucid from scripts
478bb37 Merge pull request #456 from hnyman/stat-config
e6672f0 luci-app-multiwan: mark broken as it depends on multiwan from oldpackages
4f429c5 statistics: adjust default settings to match default plugins
6a4226b statistics: cleanup config file
5ce6477 statistics: clarify CPU/processor graph by removing "idle" from it
01414949 statistics: clarify stats introduction
11a9f75 Remove ancient INSTALL file and update README.me
0ecd697 Merge pull request #454 from hnyman/fix-entropy
d820ed4 statistics: entropy plugin - fix placement of entropy.lua
c48fbfa Merge pull request #451 from hnyman/fw-zone-len
89763f9 Merge pull request #452 from hnyman/entropy
7df0df4 statistics: Add support for entropy stats
34e875b firewall: validate max length of zone name
084d435 Merge pull request #448 from hnyman/cpulabel
5f3dade Merge pull request #450 from hnyman/stat-memory
9a06498 statistics: memory plugin - improve graph by better scaling of y-axis
86ff4bd statistics: support rrdtool's alt_autoscale and alt_autoscale_max options
962cd2c statistics: cpu graph - add label definitions, add softirq and interrupt stats
37f6bd5 Merge pull request #447 from srdjanrosic/patch-1
82fecb7 Enable setting --script-security in client mode.
8597b86 Merge pull request #444 from hnyman/fixconntrack
b7b6ed7 statistics: fix ping graph label regression
ff9da6c statistics: fix conntrack regression caused by collectd 5.5.0
2a77918 http.protocol: Support filehandlers for unhandled encodings
c42bd54 Merge pull request #441 from hnyman/tz2015f
d63a7cb Timezone information: update to 2015f
bb7ea3e Merge pull request #433 from chris5560/master
0be846d ipkg.lua: compare_versions() Replace Lua Math Library call
afc5d67 Merge pull request #431 from chris5560/master
237740b cbi.lua: Fix Flag.parse() to set "self.section.changed"
fa88550 Merge pull request #429 from chris5560/master
376f038 luci-lib-nixio: pass exact sockaddr length to getnameinfo()
69ecfff contrib/community-profiles: add hameln
305528b ipkg.lua: new function compare_version
ec170d6 Fix: A disabled wireless network may be shown as enabled, when multiple networks are defined on the same radio.
159b60f Fix: Status for disabled wireless networks may display the SSID, BSSID and Mode of an active network on the same radio.
0110494 When editing an AP wireless network in LuCI, if one or more STA networks are also present on the same radio, then the channel is locked and cannot be changed for the AP. The case when all STA networks are disabled is not considered. This patch fixes the issue. Disabled networks no longer apply a lock on the channel.
48c8cad Workaround: saved administration site user and pass may appear on the Wireless configuration page, replacing the WPA key.
77acfe0 Merge pull request #428 from aa65535/master
966d87b luci-app-shadowsocks-libev: update package
3610f32 luci-mod-rpc: move luci config require into the authentication function (#427)
16047d0 luci-mod-rpc: add missing luci config require
e7f57e0 Add luci support for dnsmasq option '--servers-file'
17ab7ac Merge pull request #426 from mamarley/vnstatunderscorefix
b1b0ba5 luci-app-vnstat: Fix blank graphs for iface names with underscores
6d788d8 contrib/meshwizard: fix LAN with OLSR and DHCP
9d85b7e contrib/meshwizard: fix a bug that occured when processing list options in set_defaults()
cfd8ad8 Merge pull request #425 from aa65535/master
74b5c1b luci-mod-admin-full: restart the firewall instead of reloading it
7450103 luci-app-shadowsocks-libev: add package
30e344c fix ifname in wifi overview (freifunk public status).
bccc627 Fix routes on freifunk public status page
0ef5f3c contrib/firefunk-watchdog: fix build against musl
23dba10 Merge pull request #424 from kdarbyshirebryant/master
2d56499 Merge pull request #1 from kdarbyshirebryant/miniupnpdatupgrade
387a06b Delete luci-upnp
bae48b6 Update base.po
eac90c7 Merge pull request #419 from dangowrt/fix-olsr-json-dependency
ba897c6 luci-app-olsr: depend on luci-lib-json
e8029d6 Fix markup in Template reference
dde2504 Fix links in ThemesHowTo.md
4b11843 Add documentation converted from old Trac wiki pages
37a9d6a Merge pull request #414 from maz-1/mjpg-update
50feac8 Update base.po
3429097 Merge pull request #409 from oneru/fwknop-qr
d48f53b Merge pull request #1 from maz-1/allcommits
3bcbfb3 Merge pull request #410 from maz-1/master
8e43ab3 add chinese translations for luci-app-mjpg-streamer
0b00986 add chinese translations for luci-app-privoxy
9d69f61 Luci-app-fwknopd:add a couple config options to the interface Minor tweaks to uci-defaults refresh translation files Signed-off-by: Jonathan Bennett <JBennett@incomsystems.biz>
edf0f4f Merge pull request #402 from NeoRaider/json-empty-object
d2638a7 Merge pull request #389 from hnyman/timezone2015d
abc1ed6 Merge pull request #403 from hnyman/fix-qos-l7
1d477ab luci-app-qos: remove l7 options
304eec2 luci-lib-json: ignore null keys to allow encoding empty objects
0ef7a00 Merge pull request #401 from chris5560/master
22f40d3 luci-app-privoxy: fixed function ipkg_ver_compare()
57c5143 Merge pull request #400 from chris5560/master
e2d6ee7 luci-app-radicale: fixed function ipkg_ver_compare
a835fc0 contrib/community-profiles/augsburg: Increase leasetime and bandwidth limits
0fe4e46 applications/splash: remove set -x from splash.sh
5ef1485 modules/freifunk: fix basics cbi model
7f26be3 applications/olsr: change config file download on olsr overview page to use seperate v4 and v6 config files
77612e3 contrib/meshwizard: add ipv6only option to txtinfo/jsoninfo plugin config
516ea62 applications/olsr: redirect errors on jsoninfo connects with netcat to /dev/null to avoid spamming the log
cc39eaa applications/olsr: Get jsoninfo source port prom olsrd/olsrd6 config file
595c637 meshwizard: use different port (9091) for ipv6 jsoninfo
d447b7e add changes that were missing in the last commit
0eef467 Merge branch 'master' of github.com:openwrt/luci
458c3c1 contrib/meshwizard: fix interaction with uci in OpenWrt CC, see https://dev.openwrt.org/ticket/19539
9b5beae Merge pull request #398 from albialbi/patch-1
420cdd4 bssid und ssid scheme Anpassung für kathleen
1dada8c luci-base: prevent parsing the form input after cbi emergency save
d6d0926 Merge pull request #388 from oneru/fwknop-qr
fe14cd5 luci-base: fallback to a simple text editor if uci config cannot be loaded
03610ce luci-base: rename .gitignore to .placeholder
5014e05 Merge pull request #394 from chris5560/master
740ce09 luci-app-ddns: fixed version check
1c57ea5 luci-app-ocserv: list users with no group
c7a6830 Timezone information is updated to 2015d, released on 24 Apr 2015.
30b8097 Luci-app-fwknopd: Update uci-defaults as key-gen is now exposed in the fwknopd binary Signed-off-by: Jonathan Bennett <jbennett@incomsystems.biz>
64b728a Merge pull request #384 from nightcoffee/nightcoffee-patch-1
ec48d2d Merge pull request #385 from oneru/fwknop-qr
4ccb221 luci-app-fwknopd: Add qr code support Signed-off-by: Jonathan Bennett <jbennett@incomsystems.biz>
08a38a0 luci-base: Add cache control in index.html
f67d39e IPv6 updates
754ca29 Merge pull request #382 from chris5560/master
4cabf99 Merge pull request #380 from oneru/master
fd130d0 Add initial luci-app-fwknopd - a way to control the firewall knock daemon from luci Signed-off-by: Jonathan Bennett <jbennett@incomsystems.biz>
d3b6c37 luci-app-ddns: reflect changes on ddns-scripts
cc99288 Merge pull request #376 from chris5560/master
a708378 collections/luci: depend on luci-proto-ipv6 if IPV6 is enabled
6fb24ac Merge pull request #331 from poranje/proto=ipv6+aiccu+fixes
c38b4cd luci.mk: don't builtin translations selected by CONFIG_ALL
e6804f0 luci-app-radicale: New app to support Radicale CalDAV/CardDAV server
1c054af luci-proto-ipv6: correct aiccu options defaults
ae8e971 Merge branch 'master' of https://github.com/openwrt/luci into proto=ipv6+aiccu+fixes
4742d1c luci-proto-ipv6: fix aiccu requiretls

### CODE REVIEW

**Comment by booo** [comment]
This works great for aka. tested.

**Comment by stargieg** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi Philip

Warum wurden für fast alle feeds branches mit dem namen "for-15.05" eingerichtet?

https://github.com/openwrt/packages/tree/for-15.05
https://github.com/openwrt/luci/tree/for-15.05
https://github.com/openwrt-routing/packages/tree/for-15.05

Damit wir für eine Stabile Firmware wieder latest Master aka Bleeding edge nehmen?


Am 27.10.15 um 00:07 schrieb Philipp Borgers:
> This works great for aka. tested.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/freifunk-berlin/firmware/pull/295#issuecomment-151309935>.
> 

-----BEGIN PGP SIGNATURE-----
Version: GnuPG/MacGPG2 v2
Comment: GPGTools - http://gpgtools.org

iEYEARECAAYFAlYvUmoACgkQr9m0OkMZoqSDugCgkGmY6y8WxKOq1kid3fkZqgfB
L68An14j0zpEtUuz+kDHXeTWBMx0r6DM
=oyWO
-----END PGP SIGNATURE-----

**Comment by sarumpaet** [comment]
FWIW, auch beim openwrt-routing-Feed wurde bei Barrier Breaker der entsprechende Branch so gut wie nicht gepflegt. Ich meinte schon zu Philipp: "stable" heißt bei OpenWrt und assoziierten Projekten nicht "keine Probleme", sondern "die Bugs bleiben für Jahre die gleichen"...

Ich bin aber auch nicht überzeugt davon, jetzt OpenWrt "stable", aber LuCI master zu nehmen. Lasst uns doch wenigstens für die 0.2.0 ganz normal bei CC bleiben, außer es gibt wirklich überzeugende Gründe, das nicht zu tun. Das Changelog oben überzeugt mich jetzt nicht, ist davon irgendwas für uns kritisch?

**Comment by booo** [comment]
Deshalb habe ich die Änderung für luci zur Diskussion gestellt. Wir können auch gerne den HEAD von 15.05 nehmen. Dann würde ich den Branch anpassen und mergen, wenn es läuft?

Beim packages feed würde ich auch 15.05/cc branch nehmen.

Den routing feed würde ich trotzdem vom master nehmen, da dort nicht viel am cc branch gearbeitet wird.

**Comment by booo** [comment]
I updated the luci feed, tested and pushed it to the master branch. I'm closing this one.

**Pull request closed without merging**
