### PR TITLE
configs/common.config; build all kmods by default

### PR DESCRIPTION
**Pull request by pmelange**
As discussed at the firmware planning meeting on 12.06.2019 there was
a consensus to build all the kernel modules instead of just a select few.

see https://pad.freifunk.net/p/berlin-2019

All the kmods together take up 14MB space.

### CODE REVIEW

**Comment by SvenRoederer** [comment]
I don't think, that we need to build kmod-video* or kmod-capi* stuff, but the maintenance-overhead in managing individual CONFIG-options per module is not worth the saved bytes.

**Comment by SvenRoederer** [comment]
But with this change, we even more run into the problem if issue https://github.com/freifunk-berlin/firmware/issues/602 caused by to large buildspace needed for some buildslaves.

**Comment by pmelange** [comment]
But if we get to a unified image, then we will start saving hundreds of megabytes. :)

One option would be to build all the kmods only for releases.  This option was shortly discussed.  I'm not much of an Makefile expert.  What do you think the possibilities are of doing that?

**Comment by SvenRoederer** [comment]
For sure we can rewrite the Makefile to use other sets of configs for relases. Bur I'm strongly against this, as it will bring a big danger of having problems with releases, that have not been seen in unstable builds as of some sideeffects.

**Comment by pmelange** [comment]
Then lets concentrate on the unified image, save hundreds of megs, and let all the kmods always be built

**Comment by SvenRoederer** [comment]
In buildlog http://buildbot.berlin.freifunk.net/builders/ar71xx-generic/builds/1433 you can check on the mentioned problem of the buildspace.

**Comment by SvenRoederer** [comment]
In buildlog http://buildbot.berlin.freifunk.net/builders/ar71xx-generic/builds/1433 you can check on the mentioned problem of the buildspace.

**Pull request merged**
