### PR TITLE
common.config: addon freifunk-berlin-bbbdigger

### PR DESCRIPTION
**Pull request by pmelange**
Modified configs/common.config to add building bbbdigger as a module

### CODE REVIEW

**Comment by booo** [comment]
I think you have to update the feed.conf with the new commit hash of the firmware-packages repo to make this work.

Please start your commit messages with a verb in imperative mode: https://github.com/erlang/otp/wiki/writing-good-commit-messages

**Comment by pmelange** [comment]
I had a ready feeds.conf for a different pr (#586) and was told that was a no-go.  I like verbs too.

**Comment by booo** [comment]
There is no need to merge the master branch into this branch. We will merge it into master anyway.

Please take a look at how others write the commit messages and try to follow the good examples. E.g. don't use past and be verbose in the commit body if something is complicated or needs summary.

**Comment by booo** [comment]
Merged with 0bf262a45fe968e60e0f7bb58bc344aad70de4d2.

**Pull request closed without merging**
