### PR TITLE
build: add the new luci-app-opkg to all image types (luci-master)

### PR DESCRIPTION
**Pull request by pmelange**
The comment from the upstream commit is:
Add a new luci-app-opkg which is a feature-complete replacement for the
builtin opkg functionality of luci-mod-system using mostly client side
JavaScript to reduce the amount of server side processing.

The upstream commit in openwrt/luci is https://github.com/openwrt/luci/commit/aa2e0e2488f52b2b0acd1746ee13c7f51377f757

The freifunk-berlin issue is https://github.com/freifunk-berlin/firmware/issues/621

### CODE REVIEW

**Comment by SvenRoederer** [comment]
This is only valid for luci-master, but not for 18.06-branch.

**Comment by SvenRoederer** [comment]
We should not add this app for the "default-4MB" devices, as we remove the opkg system to gain some space.

**Comment by pmelange** [comment]
Yes, this is needed for luci-master.  Another thing is that PR https://github.com/freifunk-berlin/firmware-packages/pull/158 needs to be merged before this will work.

**Comment by pmelange** [comment]
A discussion about what to have in the 4MB images can be found in issue #626

**Comment by pmelange** [comment]
Oh, I see new what you mean about the 4MB devices.  There is another commit on it's way

**Comment by pmelange** [comment]
I left luci-app-opkg for the backbone_4MB targets since opkg is still added to these images

**Comment by pmelange** [comment]
This commit needs to be reverted.  The luci-app-opkg package is only to be found on the luci master branch (our master is on the 18.x branch).  When OpenWrt 19.x is ready, then this commit should be merged.

Also note, the milestone is Hedy-1.2.0

@sarumpaet can you take care of the revert and restoring the branch?

**Comment by sarumpaet** [comment]
Milestones have been largely fiction so far.
If you don't want something merged, please add "do not merge" to the PR subject.

**Comment by pmelange** [comment]
comment has been updated.  But I guess a new PR is needed since this one is closed.

**Comment by pmelange** [comment]
the new PR is https://github.com/freifunk-berlin/firmware/pull/692

**Comment by sarumpaet** [comment]
Thx and sorry!

**Comment by pmelange** [comment]
no problem.

**Pull request merged**
