### PR TITLE
[RFC] add PATCHES.rst to introduce a counting structure

### PR DESCRIPTION
**Pull request by lynxis**
helps maintaining our patches when backported patch comes first

### CODE REVIEW

**Comment by booo** [comment]
We can give this a try. Can you merge a markdown version of this to stay consistent with the other files?

**Comment by SvenRoederer** [comment]
what about :
- 0xx - openWRT / LEDE related (upstream)
- 1xx - packages (upstream)
- 2xx - LUCI (upstream)
- 3xx - routing (upstream)
- (4xx, 5xx - reserved)
- 6xx - build system changes to support this build system
- 7xx - freifunk specific
- 8xx - other
- (9xx - reserved)

**Comment by lynxis** [comment]
sounds nice.

**Comment by booo** [comment]
We can try. Can someone create a commit?

**Comment by SvenRoederer** [comment]
please look at branch feature/#359 for this

**Comment by lynxis** [comment]
superseeded.

**Pull request closed without merging**
